- name: Create sonar-scanner-cli directory
  become: true
  ansible.builtin.file:
    path: /opt/sonar-scanner-cli
    state: directory
- name: Download sonar-scanner-cli
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/SonarSource/sonar-scanner-cli/archive/refs/tags/{{ sonar_scanner_version }}.tar.gz
    dest: /opt/sonar-scanner-cli
    remote_src: yes
- name: Add sonar-scanner to PATH
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/sonar-scanner.sh
    content: "PATH=$PATH:/opt/sonar-scanner-cli/sonar-scanner-{{ sonar_scanner_version }}-linux/bin"
    mode: u=rw,g=r,o=r
