- name: Install dependency
  ansible.builtin.include_role:
    name: gpg
- name: Add gh apt signing key
  become: true
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: "0644"
    force: true

- name: Add gh apt repository
  vars:
    deb_architecture: {
      "aarch64": "arm64",
      "x86_64": "amd64"
    }
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ [ansible_architecture] | map('extract', deb_architecture) | first }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages {{ ansible_distribution_release }} main"
    state: present
- name: Install gh
  become: true
  apt:
    name: gh
    state: present
