collections:
  - name: community.general
    version: 7.2.1
  - name: ansible.posix
    version: 1.5.4
  - name: community.mysql
    version: 3.7.2
  - name: community.postgresql
    version: 3.2.0
roles:
  - name: andrelohmann.nodesource
    version: v3.0.2
