collections:
  - name: community.general
    version: 6.4.0
  - name: ansible.posix
    version: 1.4.0
  - name: community.mysql
    version: 3.5.1
  - name: community.postgresql
    version: 2.2.0
roles:
  - name: andrelohmann.nodesource
    version: 2.0.0
