collections:
  - name: community.general
    version: 6.4.0
  - name: ansible.posix
    version: 1.5.1
  - name: community.mysql
    version: 3.6.0
  - name: community.postgresql
    version: 2.3.2
roles:
  - name: andrelohmann.nodesource
    version: 2.0.0
