- name: Install buildkit
  become: true
  ansible.builtin.unarchive:
    src: "{{ buildkit_url }}"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=1
  tags: buildkit
