- name: Add terraform Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
- name: Install terraform
  become: true
  apt:
    name: terraform
    state: present
