# https://cloud.google.com/sdk/docs/install#deb
- name: Install gcloud dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - libffi-dev #https://stackoverflow.com/questions/62658237/it-seems-that-the-version-of-the-libffi-library-seen-at-runtime-is-different-fro

- name: Add an Apt google cloud signing key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg

- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present

- name: Install google-cloud-sdk
  become: true
  apt:
    name: google-cloud-sdk
    state: present
