- name: install anaconda deps
  become: true
  apt:
    pkg:
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxrandr2
      - libxrandr2
      - libxss1
      - libxcursor1
      - libxcomposite1
      - libasound2
      - libxi6
      - libxtst6
