- name: Install dependencies
  become: true
  apt:
    pkg:
      - make
      - git
      - gcc
      - build-essential
      - pkgconf
      - libtool
      - libsystemd-dev
      - libprotobuf-c-dev
      - libcap-dev
      - libseccomp-dev
      - libyajl-dev
      - go-md2man
      - autoconf
      - python3
      - automake
    state: present
