---
- name: Talk to host just so we can learn about it
  hosts: all
  tasks:
    - name: Classify host depending on its OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
- hosts: os_Ubuntu
  tasks:
    - name: Add or modify nofile soft limit
      become: yes
      community.general.pam_limits:
        domain: "*"
        limit_type: soft
        limit_item: nofile
        value: 10000

    - import_role:
        name: crun
    - import_role:
        name: buildkit
    - import_role:
        name: buildkit
        tasks_from: start
      vars:
        buildkit_addr: tcp://0.0.0.0:1234
        oci_worker_binary: crun
