name: roles_python_files_flask
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Run ci
        uses: dagger/dagger-for-github@v3
        with:
          version: 0.2.25
          cmds: |
            echo "Running ci"
            ls -la
