name: roles_react_files_cra_typescript
on:
  push:
    paths:
      - roles/react/files/cra/typescript/**
      - .github/workflows/roles_react_files_cra_typescript.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 19 # renovate: datasource=docker depName=node versioning=docker
      IMAGE: ghcr.io/${{ github.repository }}-cra-typescript

    steps:
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clone repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install dependencies
        run: npm ci

      - name: Set PUSH_IMAGE
        if: endsWith(github.ref, '/master')
        run: echo "PUSH_IMAGE=True" >> $GITHUB_ENV

      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI
        run: npx ts-node --esm roles/react/files/cra/typescript/ci.mts
