name: roles_python_files_fastapi
on:
  push:
    paths:
      - roles/python/files/fastapi/**
      - .github/workflows/roles_python_files_fastapi.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11 # renovate: datasource=docker depName=python versioning=docker
      IMAGE: ghcr.io/${{ github.repository }}-fastapi

    steps:
      - name: Setup python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PUSH_IMAGE
        if: endsWith(github.ref, '/master')
        run: echo "PUSH_IMAGE=True" >> $GITHUB_ENV

      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI
        run: python roles/python/files/fastapi/ci.py
