name: roles

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11 # renovate: datasource=docker depName=python versioning=docker
    steps:
      - name: Setup python
        uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CI
        run: python ci.py
