name: roles_python_files_flask
on:
  push:
    paths:
      - roles/python/files/flask/**
      - .github/workflows/roles_python_files_flask.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12 # renovate: datasource=docker depName=python versioning=docker
      IMAGE: ghcr.io/${{ github.repository }}-flask

    steps:
      - name: Setup python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PUSH_IMAGE
        if: endsWith(github.ref, '/master')
        run: echo "PUSH_IMAGE=True" >> $GITHUB_ENV

      - uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI
        run: python roles/python/files/flask/ci.py
