name: roles_python_files_flask
on:
  push:
    paths:
      - roles/python/files/flask/**
      - .github/workflows/roles_python_files_flask.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12 # renovate: datasource=docker depName=python versioning=docker
      IMAGE: ghcr.io/${{ github.repository }}-flask

    steps:
      - name: Setup python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set PUSH_IMAGE
        if: endsWith(github.ref, '/master')
        run: echo "PUSH_IMAGE=True" >> $GITHUB_ENV

      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CI
        run: python roles/python/files/flask/ci.py
