name: roles

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.12 # renovate: datasource=docker depName=python versioning=docker
    steps:
      - name: Setup python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CI
        run: python ci.py
