name: roles_python_files_flask
on:
  push:
    paths:
      - roles/python/files/flask/**
      - .github/workflows/roles_python_files_flask.yaml
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DAGGER_VERSION: 0.2.27 # renovate: datasource=github-releases lookupName=dagger/dagger versioning=docker
      DAGGER_CACHE_FROM: type=gha,scope=dagger_cache_roles_python_files_flask
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger_cache_roles_python_files_flask
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run tests
        if: github.ref != 'refs/heads/master'
        uses: dagger/dagger-for-github@v3
        with:
          version: ${{ env.DAGGER_VERSION }}
          workdir: ./roles/python/files/flask
          cmds: |
            project update
            do test

      - name: Run tests and push image
        if: github.ref == 'refs/heads/master'
        env:
          REGISTRY_IMAGE: ghcr.io/${{ github.repository }}-python-flask
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        uses: dagger/dagger-for-github@v3
        with:
          version: ${{ env.DAGGER_VERSION }}
          workdir: ./roles/python/files/flask
          cmds: |
            project update
            do push
