name: roles_dagger_files_image

on:
  push:
    paths:
      - roles/dagger/files/image/**
      - .github/workflows/roles_dagger_files_image.yaml
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      DAGGER_RELEASE_VERSION: v0.2.26 # renovate: datasource=github-releases depName=dagger lookupName=dagger/dagger versioning=docker
      DAGGER_VERSION: 0.2.26
      DAGGER_CACHE_FROM: type=gha,scope=dagger_cache_roles_dagger_files_image
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger_cache_roles_dagger_files_image
    steps:
      - name: Clone repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Run tests
        if: github.ref != 'refs/heads/master'
        uses: dagger/dagger-for-github@46924d81463a52e60895f90b1ae6d89394ccb69c # tag=v3
        with:
          version: ${{ env.DAGGER_VERSION }}
          workdir: ./roles/dagger/files/image
          cmds: |
            project update
            do test

      - name: Run tests and push tagged image
        if: github.ref == 'refs/heads/master'
        env:
          IMAGE: ghcr.io/${{ github.repository }}-dagger:${{ env.DAGGER_VERSION }}
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        uses: dagger/dagger-for-github@46924d81463a52e60895f90b1ae6d89394ccb69c # tag=v3
        with:
          version: ${{ env.DAGGER_VERSION }}
          workdir: ./roles/dagger/files/image
          cmds: |
            project update
            do push

      - name: Run tests and push latest image
        if: github.ref == 'refs/heads/master'
        env:
          IMAGE: ghcr.io/${{ github.repository }}-dagger
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        uses: dagger/dagger-for-github@46924d81463a52e60895f90b1ae6d89394ccb69c # tag=v3
        with:
          version: ${{ env.DAGGER_VERSION }}
          workdir: ./roles/dagger/files/image
          cmds: |
            project update
            do push
