name: roles

on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.11 # renovate: datasource=docker depName=python versioning=docker
    steps:
      - name: Setup python
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Clone repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CI
        run: python ci.py
