name: vagrant

on: push
jobs:
  ci:
    runs-on: macos-12
    env:
      ANSIBLE_CORE_VERSION: 2.13.2 # renovate: datasource=pypi depName=ansible-core versioning=pep440
      DAGGER_RELEASE_VERSION: v0.2.28 # renovate: datasource=github-releases depName=dagger lookupName=dagger/dagger versioning=docker
      DAGGER_CACHE_FROM: type=gha,scope=dagger_cache_vagrant
      DAGGER_CACHE_TO: type=gha,mode=max,scope=dagger_cache_vagrant
    steps:
      - name: Clone repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Cache Vagrant boxes
        uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Show Vagrant version
        run: vagrant --version

      - name: Install ansible
        run: python3 -m pip install ansible-core==${{ env.ANSIBLE_CORE_VERSION }}

      - name: Install requirements.yml
        run: ansible-galaxy install -r requirements.yml

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: vagrant ssh -c "echo 'hello world!'"

      - name: Set vars
        id: vars
        run: |
          echo ::set-output name=DAGGER_VERSION::${DAGGER_RELEASE_VERSION:1}
          echo ::set-output name=VAGRANT_HOST::$(python3 roles/vagrant/files/get_host.py)
      - name: Run tests
        uses: dagger/dagger-for-github@46924d81463a52e60895f90b1ae6d89394ccb69c # tag=v3
        env:
          BUILDKIT_HOST: tcp://${{ steps.vars.outputs.VAGRANT_HOST }}:1234
        with:
          version: ${{ steps.vars.outputs.DAGGER_VERSION }}
          cmds: |
            project update
            do test
